/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PathwaysRouteImport } from './routes/pathways'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ImportReviewRouteImport } from './routes/import-review'
import { Route as HubRouteImport } from './routes/hub'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as FactionsRouteImport } from './routes/factions'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as CanonRouteImport } from './routes/canon'
import { Route as IndexRouteImport } from './routes/index'

const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwaysRoute = PathwaysRouteImport.update({
  id: '/pathways',
  path: '/pathways',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportReviewRoute = ImportReviewRouteImport.update({
  id: '/import-review',
  path: '/import-review',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const FactionsRoute = FactionsRouteImport.update({
  id: '/factions',
  path: '/factions',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const CanonRoute = CanonRouteImport.update({
  id: '/canon',
  path: '/canon',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canon': typeof CanonRoute
  '/characters': typeof CharactersRoute
  '/factions': typeof FactionsRoute
  '/glossary': typeof GlossaryRoute
  '/hub': typeof HubRoute
  '/import-review': typeof ImportReviewRoute
  '/inbox': typeof InboxRoute
  '/locations': typeof LocationsRoute
  '/pathways': typeof PathwaysRoute
  '/projects': typeof ProjectsRoute
  '/timeline': typeof TimelineRoute
  '/trash': typeof TrashRoute
  '/uploads': typeof UploadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canon': typeof CanonRoute
  '/characters': typeof CharactersRoute
  '/factions': typeof FactionsRoute
  '/glossary': typeof GlossaryRoute
  '/hub': typeof HubRoute
  '/import-review': typeof ImportReviewRoute
  '/inbox': typeof InboxRoute
  '/locations': typeof LocationsRoute
  '/pathways': typeof PathwaysRoute
  '/projects': typeof ProjectsRoute
  '/timeline': typeof TimelineRoute
  '/trash': typeof TrashRoute
  '/uploads': typeof UploadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canon': typeof CanonRoute
  '/characters': typeof CharactersRoute
  '/factions': typeof FactionsRoute
  '/glossary': typeof GlossaryRoute
  '/hub': typeof HubRoute
  '/import-review': typeof ImportReviewRoute
  '/inbox': typeof InboxRoute
  '/locations': typeof LocationsRoute
  '/pathways': typeof PathwaysRoute
  '/projects': typeof ProjectsRoute
  '/timeline': typeof TimelineRoute
  '/trash': typeof TrashRoute
  '/uploads': typeof UploadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canon'
    | '/characters'
    | '/factions'
    | '/glossary'
    | '/hub'
    | '/import-review'
    | '/inbox'
    | '/locations'
    | '/pathways'
    | '/projects'
    | '/timeline'
    | '/trash'
    | '/uploads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canon'
    | '/characters'
    | '/factions'
    | '/glossary'
    | '/hub'
    | '/import-review'
    | '/inbox'
    | '/locations'
    | '/pathways'
    | '/projects'
    | '/timeline'
    | '/trash'
    | '/uploads'
  id:
    | '__root__'
    | '/'
    | '/canon'
    | '/characters'
    | '/factions'
    | '/glossary'
    | '/hub'
    | '/import-review'
    | '/inbox'
    | '/locations'
    | '/pathways'
    | '/projects'
    | '/timeline'
    | '/trash'
    | '/uploads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanonRoute: typeof CanonRoute
  CharactersRoute: typeof CharactersRoute
  FactionsRoute: typeof FactionsRoute
  GlossaryRoute: typeof GlossaryRoute
  HubRoute: typeof HubRoute
  ImportReviewRoute: typeof ImportReviewRoute
  InboxRoute: typeof InboxRoute
  LocationsRoute: typeof LocationsRoute
  PathwaysRoute: typeof PathwaysRoute
  ProjectsRoute: typeof ProjectsRoute
  TimelineRoute: typeof TimelineRoute
  TrashRoute: typeof TrashRoute
  UploadsRoute: typeof UploadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathways': {
      id: '/pathways'
      path: '/pathways'
      fullPath: '/pathways'
      preLoaderRoute: typeof PathwaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-review': {
      id: '/import-review'
      path: '/import-review'
      fullPath: '/import-review'
      preLoaderRoute: typeof ImportReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factions': {
      id: '/factions'
      path: '/factions'
      fullPath: '/factions'
      preLoaderRoute: typeof FactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canon': {
      id: '/canon'
      path: '/canon'
      fullPath: '/canon'
      preLoaderRoute: typeof CanonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanonRoute: CanonRoute,
  CharactersRoute: CharactersRoute,
  FactionsRoute: FactionsRoute,
  GlossaryRoute: GlossaryRoute,
  HubRoute: HubRoute,
  ImportReviewRoute: ImportReviewRoute,
  InboxRoute: InboxRoute,
  LocationsRoute: LocationsRoute,
  PathwaysRoute: PathwaysRoute,
  ProjectsRoute: ProjectsRoute,
  TimelineRoute: TimelineRoute,
  TrashRoute: TrashRoute,
  UploadsRoute: UploadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
